"""Updated User model

Revision ID: 115d21e8e4ae
Revises: 363631fe26ec
Create Date: 2025-04-20 19:55:55.346637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115d21e8e4ae'
down_revision = '363631fe26ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
